
namespace Yu_Gi_Oh_LOTD_LE_Deck_Manager.Services
{

    public static class OwnerDatabase
    {
        private static readonly Dictionary<byte, string> _idToName = new()
    {
        { 1,   "Akiza Izinski" },       { 2,   "Andre" },
        { 3,   "Antinomy" },            { 4,   "Aporia" },
        { 5,   "Bolt Tanner" },         { 6,   "Breo" },
        { 7,   "Broder" },              
        { 9,   "Carly Carmine" },       { 10,  "Crow Hogan" },
        { 11,  "Devack" },              { 12,  "Dragan" },
        { 13,  "Greiger" },             { 14,  "Halldor" },
        { 15,  "Hunter Pace" },         { 16,  "Jack Atlas" },
                                        { 18,  "Jean" },
        { 19,  "Kalin Kessler" },       
        { 21,  "Leo" },                 
        { 23,  "Lester" },              
        { 25,  "Misty Tredwell" },      { 26,  "Mr. Armstrong" },
        { 27,  "Primo" },               
        { 29,  "Rex Goodwin" },         { 30,  "Roman Goodwin" },
        { 31,  "Sayer" },               { 32,  "Sherry LeBlanc" },
                                        { 34,  "Tetsu Trudge" },
        { 35,  "Yusei Fudo" },          { 36,  "Zone" },
        { 37,  "Alexis Rhodes" },       { 38,  "Aster Phoenix" },
        { 39,  "Aura Sentia" },         { 40,  "Celina" },
        { 41,  "Chojiro Tokumatsu" },   { 42,  "Crow Hogan" },
        { 43,  "Declan Akaba" },        { 44,  "Dennis McField" },
        { 45,  "Officer 227" },         
        { 47,  "Gong Strong" },         
        { 49,  "Dipper O'rion" },       { 50,  "Jack Atlas" },
        { 51,  "Jean Michel Roget" },   { 52,  "Kite Tenjo" },
                                        { 54,  "Lulu" },
        { 55,  "Julia Krystal" },       
        { 57,  "Obelisk Force" },       
                                        { 60,  "Rin" },
        { 61,  "Shay Obsidian" },       { 62,  "Sylvio Sawatari" },
                                        { 64,  "The Sledgehammer" },
        { 65,  "Sora Perse" },          { 66,  "Moon Shadow" },
        { 67,  "Kit Blade" },           { 68,  "Yugo" },
        { 69,  "Yuri" },                { 70,  "Yusho Sakaki" },
        { 71,  "Yuto" },                { 72,  "Yuya Sakaki" },
        { 73,  "Zuzu Boyle" },          { 74,  "Z-ARC" },
        { 75,  "Alister" },             { 76,  "Arkana" },
        { 77,  "Bandit Keith" },        { 78,  "Bonz" },
        { 79,  "Dartz" },               { 80,  "Ishizu Ishtar" },
        { 81,  "Joey Wheeler" },        { 82,  "Mai Valentine" },
        { 83,  "Mako Tsunami" },        { 84,  "Maximillion Pegasus" },
        { 89,  "Odion" },               { 90,  "PaniK" },
        { 91,  "Rafael" },              { 92,  "Rex Raptor" },
        { 93,  "Seeker" },              { 94,  "Seto Kaiba" },
        { 97,  "Strings" },             { 98,  "Téa Gardner" },
                                        { 100, "Valon" },
        { 101, "Weevil Underwood" },    { 102, "Yami Bakura" },
        { 103, "Yami Marik" },          { 104, "Yami Yugi" },
        { 105, "Yugi Muto" },           { 106, "Adrian Gecko" },
        { 107, "Alexis Rhodes" },       { 108, "Amnael" },
        { 109, "Aster Phoenix" },       { 110, "Masked Atticus" },
        { 111, "Atticus Rhodes" },      { 112, "Axel Brodie" },
        { 113, "Bastion Misawa" },      { 114, "Blair Flannigan" },
                                        { 116, "Camula" },
        { 117, "Chazz Princeton" },     { 118, "Chumley Huffington" },
        { 119, "Jaden Yuki" },          { 120, "Jesse Anderson" },
        { 121, "Jim Crocodile Cook" },  { 122, "Kagemaru" },
        { 123, "Marcel Bonaparte" },    { 124, "Nightshroud" },
                                        { 126, "Sartorius Kumar" },
        { 127, "Chancellor Sheppard" }, { 128, "Syrus Truesdale" },
        { 129, "Tania" },               { 130, "Prof. Thelonious Viper" },
        { 131, "Titan" },               { 132, "Tyranno Hassleberry" },
        { 133, "Dr. Vellian Crowler" }, 
                                        { 136, "Yubel" },
        { 137, "Zane Truesdale" },      { 138, "IN4-M8" },
        { 139, "INF-N8" },              { 140, "Blue Angel" },
        { 141, "The Gore" },            { 142, "Knight of Hanoi" },
        { 143, "Playmaker" },           { 144, "Alito" },
        { 145, "Anna Kaboom" },         { 146, "Astral" },
        { 147, "Bronk Stone" },         { 148, "Cathy Katherine" },
        { 149, "Dextra" },              { 150, "Don Thousand" },
        { 151, "Dr. Faker" },           { 152, "Dumon" },
        { 153, "Flip Turner" },         { 154, "Girag" },
                                        { 156, "Kite Tenjo" },
                                        { 158, "Mizar" },
                                        { 160, "Nash" },
        { 161, "Nelson Andrews" },      { 162, "Nistro" },
        { 163, "Number 96" },           
        { 165, "Quattro" },             { 166, "Quinton" },
        { 167, "Ray Shadows" },         { 168, "Reginald Kastle" },
        { 169, "Rio Kastle" },          
        { 171, "Trey" },                { 172, "Vector" },
        { 173, "Vetrix" },              { 174, "Yuma Tsukumo" },
        { 175, "ZEXAL" },               { 176, "ZEXAL 3" },
        { 177, "Ai" },                  { 178, "Akira Zaizen" },
        { 179, "The Shepherd" },        { 180, "Blue Gal" },
        { 181, "Blue Maiden" },         { 182, "Bohman" },
        { 183, "Ghost Gal" },           { 184, "The Gore" },
        { 185, "Lightning" },           { 186, "Roboppi" },
        { 187, "Soulburner" },          { 188, "Spectre" },
        { 189, "Varis" },               { 190, "Varis" },
        { 191, "Windy" },
    };

        public static string GetName(byte id) =>
            _idToName.TryGetValue(id, out var name) ? name : $"Unknown ({id})";

        public static IEnumerable<KeyValuePair<byte, string>> All => _idToName;

    }
}