<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Yu_Gi_Oh_LOTD_LE_Deck_Manager</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<ApplicationManifest>app.manifest</ApplicationManifest>
	<ApplicationIcon>favicon.ico</ApplicationIcon>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\cards\Cards.json" />
    <None Remove="Assets\characters\0.png" />
    <None Remove="Assets\characters\1.png" />
    <None Remove="Assets\characters\10.png" />
    <None Remove="Assets\characters\100.png" />
    <None Remove="Assets\characters\101.png" />
    <None Remove="Assets\characters\102.png" />
    <None Remove="Assets\characters\103.png" />
    <None Remove="Assets\characters\104.png" />
    <None Remove="Assets\characters\105.png" />
    <None Remove="Assets\characters\106.png" />
    <None Remove="Assets\characters\107.png" />
    <None Remove="Assets\characters\108.png" />
    <None Remove="Assets\characters\109.png" />
    <None Remove="Assets\characters\11.png" />
    <None Remove="Assets\characters\110.png" />
    <None Remove="Assets\characters\111.png" />
    <None Remove="Assets\characters\112.png" />
    <None Remove="Assets\characters\113.png" />
    <None Remove="Assets\characters\114.png" />
    <None Remove="Assets\characters\116.png" />
    <None Remove="Assets\characters\117.png" />
    <None Remove="Assets\characters\118.png" />
    <None Remove="Assets\characters\119.png" />
    <None Remove="Assets\characters\12.png" />
    <None Remove="Assets\characters\120.png" />
    <None Remove="Assets\characters\121.png" />
    <None Remove="Assets\characters\122.png" />
    <None Remove="Assets\characters\123.png" />
    <None Remove="Assets\characters\124.png" />
    <None Remove="Assets\characters\126.png" />
    <None Remove="Assets\characters\127.png" />
    <None Remove="Assets\characters\128.png" />
    <None Remove="Assets\characters\129.png" />
    <None Remove="Assets\characters\13.png" />
    <None Remove="Assets\characters\130.png" />
    <None Remove="Assets\characters\131.png" />
    <None Remove="Assets\characters\132.png" />
    <None Remove="Assets\characters\133.png" />
    <None Remove="Assets\characters\136.png" />
    <None Remove="Assets\characters\137.png" />
    <None Remove="Assets\characters\138.png" />
    <None Remove="Assets\characters\139.png" />
    <None Remove="Assets\characters\14.png" />
    <None Remove="Assets\characters\140.png" />
    <None Remove="Assets\characters\141.png" />
    <None Remove="Assets\characters\142.png" />
    <None Remove="Assets\characters\143.png" />
    <None Remove="Assets\characters\144.png" />
    <None Remove="Assets\characters\145.png" />
    <None Remove="Assets\characters\146.png" />
    <None Remove="Assets\characters\147.png" />
    <None Remove="Assets\characters\148.png" />
    <None Remove="Assets\characters\149.png" />
    <None Remove="Assets\characters\15.png" />
    <None Remove="Assets\characters\150.png" />
    <None Remove="Assets\characters\151.png" />
    <None Remove="Assets\characters\152.png" />
    <None Remove="Assets\characters\153.png" />
    <None Remove="Assets\characters\154.png" />
    <None Remove="Assets\characters\156.png" />
    <None Remove="Assets\characters\158.png" />
    <None Remove="Assets\characters\16.png" />
    <None Remove="Assets\characters\160.png" />
    <None Remove="Assets\characters\161.png" />
    <None Remove="Assets\characters\162.png" />
    <None Remove="Assets\characters\163.png" />
    <None Remove="Assets\characters\165.png" />
    <None Remove="Assets\characters\166.png" />
    <None Remove="Assets\characters\167.png" />
    <None Remove="Assets\characters\168.png" />
    <None Remove="Assets\characters\169.png" />
    <None Remove="Assets\characters\171.png" />
    <None Remove="Assets\characters\172.png" />
    <None Remove="Assets\characters\173.png" />
    <None Remove="Assets\characters\174.png" />
    <None Remove="Assets\characters\175.png" />
    <None Remove="Assets\characters\176.png" />
    <None Remove="Assets\characters\177.png" />
    <None Remove="Assets\characters\178.png" />
    <None Remove="Assets\characters\179.png" />
    <None Remove="Assets\characters\18.png" />
    <None Remove="Assets\characters\180.png" />
    <None Remove="Assets\characters\181.png" />
    <None Remove="Assets\characters\182.png" />
    <None Remove="Assets\characters\183.png" />
    <None Remove="Assets\characters\184.png" />
    <None Remove="Assets\characters\185.png" />
    <None Remove="Assets\characters\186.png" />
    <None Remove="Assets\characters\187.png" />
    <None Remove="Assets\characters\188.png" />
    <None Remove="Assets\characters\189.png" />
    <None Remove="Assets\characters\19.png" />
    <None Remove="Assets\characters\190.png" />
    <None Remove="Assets\characters\191.png" />
    <None Remove="Assets\characters\2.png" />
    <None Remove="Assets\characters\21.png" />
    <None Remove="Assets\characters\23.png" />
    <None Remove="Assets\characters\25.png" />
    <None Remove="Assets\characters\26.png" />
    <None Remove="Assets\characters\27.png" />
    <None Remove="Assets\characters\29.png" />
    <None Remove="Assets\characters\3.png" />
    <None Remove="Assets\characters\30.png" />
    <None Remove="Assets\characters\31.png" />
    <None Remove="Assets\characters\32.png" />
    <None Remove="Assets\characters\34.png" />
    <None Remove="Assets\characters\35.png" />
    <None Remove="Assets\characters\36.png" />
    <None Remove="Assets\characters\37.png" />
    <None Remove="Assets\characters\38.png" />
    <None Remove="Assets\characters\39.png" />
    <None Remove="Assets\characters\4.png" />
    <None Remove="Assets\characters\40.png" />
    <None Remove="Assets\characters\41.png" />
    <None Remove="Assets\characters\42.png" />
    <None Remove="Assets\characters\43.png" />
    <None Remove="Assets\characters\44.png" />
    <None Remove="Assets\characters\45.png" />
    <None Remove="Assets\characters\47.png" />
    <None Remove="Assets\characters\49.png" />
    <None Remove="Assets\characters\5.png" />
    <None Remove="Assets\characters\50.png" />
    <None Remove="Assets\characters\51.png" />
    <None Remove="Assets\characters\52.png" />
    <None Remove="Assets\characters\54.png" />
    <None Remove="Assets\characters\55.png" />
    <None Remove="Assets\characters\57.png" />
    <None Remove="Assets\characters\6.png" />
    <None Remove="Assets\characters\60.png" />
    <None Remove="Assets\characters\61.png" />
    <None Remove="Assets\characters\62.png" />
    <None Remove="Assets\characters\64.png" />
    <None Remove="Assets\characters\65.png" />
    <None Remove="Assets\characters\66.png" />
    <None Remove="Assets\characters\67.png" />
    <None Remove="Assets\characters\68.png" />
    <None Remove="Assets\characters\69.png" />
    <None Remove="Assets\characters\7.png" />
    <None Remove="Assets\characters\70.png" />
    <None Remove="Assets\characters\71.png" />
    <None Remove="Assets\characters\72.png" />
    <None Remove="Assets\characters\73.png" />
    <None Remove="Assets\characters\74.png" />
    <None Remove="Assets\characters\75.png" />
    <None Remove="Assets\characters\76.png" />
    <None Remove="Assets\characters\77.png" />
    <None Remove="Assets\characters\78.png" />
    <None Remove="Assets\characters\79.png" />
    <None Remove="Assets\characters\80.png" />
    <None Remove="Assets\characters\81.png" />
    <None Remove="Assets\characters\82.png" />
    <None Remove="Assets\characters\83.png" />
    <None Remove="Assets\characters\84.png" />
    <None Remove="Assets\characters\89.png" />
    <None Remove="Assets\characters\9.png" />
    <None Remove="Assets\characters\90.png" />
    <None Remove="Assets\characters\91.png" />
    <None Remove="Assets\characters\92.png" />
    <None Remove="Assets\characters\93.png" />
    <None Remove="Assets\characters\94.png" />
    <None Remove="Assets\characters\97.png" />
    <None Remove="Assets\characters\98.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\cards\Cards.json" />
    <EmbeddedResource Include="Assets\characters\0.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\10.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\100.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\101.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\102.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\103.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\104.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\105.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\106.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\107.png" />
    <EmbeddedResource Include="Assets\characters\108.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\109.png" />
    <EmbeddedResource Include="Assets\characters\11.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\110.png" />
    <EmbeddedResource Include="Assets\characters\111.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\112.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\113.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\114.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\116.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\117.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\118.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\119.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\12.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\120.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\121.png" />
    <EmbeddedResource Include="Assets\characters\122.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\123.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\124.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\126.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\127.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\128.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\129.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\13.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\130.png" />
    <EmbeddedResource Include="Assets\characters\131.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\132.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\133.png" />
    <EmbeddedResource Include="Assets\characters\136.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\137.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\138.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\139.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\14.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\140.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\141.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\142.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\143.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\144.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\145.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\146.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\147.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\148.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\149.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\15.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\150.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\151.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\152.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\153.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\154.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\156.png" />
    <EmbeddedResource Include="Assets\characters\158.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\16.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\160.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\161.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\162.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\163.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\165.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\166.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\167.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\168.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\169.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\171.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\172.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\173.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\174.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\175.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\176.png" />
    <EmbeddedResource Include="Assets\characters\177.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\178.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\179.png" />
    <EmbeddedResource Include="Assets\characters\18.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\180.png" />
    <EmbeddedResource Include="Assets\characters\181.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\182.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\183.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\184.png" />
    <EmbeddedResource Include="Assets\characters\185.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\186.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\187.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\188.png" />
    <EmbeddedResource Include="Assets\characters\189.png" />
    <EmbeddedResource Include="Assets\characters\19.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\190.png" />
    <EmbeddedResource Include="Assets\characters\191.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\21.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\23.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\25.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\26.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\27.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\29.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\30.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\31.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\32.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\34.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\35.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\36.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\37.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\38.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\39.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\40.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\41.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\42.png" />
    <EmbeddedResource Include="Assets\characters\43.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\44.png" />
    <EmbeddedResource Include="Assets\characters\45.png" />
    <EmbeddedResource Include="Assets\characters\47.png" />
    <EmbeddedResource Include="Assets\characters\49.png" />
    <EmbeddedResource Include="Assets\characters\5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\50.png" />
    <EmbeddedResource Include="Assets\characters\51.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\52.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\54.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\55.png" />
    <EmbeddedResource Include="Assets\characters\57.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\6.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\60.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\61.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\62.png" />
    <EmbeddedResource Include="Assets\characters\64.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\65.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\66.png" />
    <EmbeddedResource Include="Assets\characters\67.png" />
    <EmbeddedResource Include="Assets\characters\68.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\69.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\7.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\70.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\71.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\72.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\73.png" />
    <EmbeddedResource Include="Assets\characters\74.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\75.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\76.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\77.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\78.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\79.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\80.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\81.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\82.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\83.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\84.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\89.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\9.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\90.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\91.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\92.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\93.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\94.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\97.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\characters\98.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReaLTaiizor" Version="3.8.1.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>